config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions" }
  root to: "pages#home"

  get '/choose_restaurant', to: 'pages#choose_restaurant'
  get '/assign_restaurant', to: 'pages#assign_restaurant'

  resources :sitting_areas, only: [:show] do
    resources :items, only: %i[create]
    resources :orders, only: %i[new show] do
      collection do
        get :add_order
        get :remove_order
      end
    end
  end

  resources :orders, only: %i[update destroy ] do
    member do
      post :toggle_status
    end
    collection do
      patch :update_all
    end
  end

  resources :restaurants, except: [:index]
end

app/models/sitting_area.rb
class SittingArea < ApplicationRecord
  belongs_to :restaurant
  has_many :orders
end

app/controllers/sitting_areas_controller.rb
class SittingAreasController < ApplicationController
  def show
    @sitting_area = SittingArea.find(params[:id])
    @restaurant = @sitting_area.restaurant
    @pending_orders = @sitting_area.orders.where(status: "en attente")
    @passed_orders = @sitting_area.orders - @pending_orders
  end
end

app/views/sitting_areas/show.html.erb
<%= render "shared/banner_client", restaurant: @restaurant, sitting_area: @sitting_area %>

<div class="container-fluid mb-5">
  <h2 class="py-2 text-center"> Que pouvons-nous faire pour vous ? </h2>

  <div class="row mx-0" style="text-decoration: none;">
    <% Category.all.each do |category| %>
      <div class="col-6">
        <%= link_to new_sitting_area_order_path(@sitting_area, category_id: category.id), class: "d-block btn #{category.name}-background mb-4 py-3", style: "border-radius: 5px; box-shadow: 2px 2px 5px rgba(0,0,0,0.3);" do %>
          <span>
            <%= image_tag "#{category.name}.png", style: 'height:70px;width:70px;'%>
            <br>
            <%= category.name %>
          </span>
        <% end %>
      </div>
    <% end %>
    <div class="col-6 text-center">
      <!-- Button trigger modal -->
      <div type="button" class= "autre d-block btn btn-primary mb-4 py-3", style= "border-radius: 5px; box-shadow: 2px 2px 5px rgba(0,0,0,0.3);" data-bs-toggle="modal" data-bs-target="#exampleModal">
        <%= image_tag "custom.png", alt:"Custom Icon", style:"height:70px;width:70px;position:relative;left:6px"%>
        <br>
        Autres
      </div>
    </div>
  </div>

  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Que voulez vous ?</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <%= simple_form_for :item, url: sitting_area_items_path(@sitting_area), method: :post do |f| %>
            <%= f.input :name, label: "Votre demande"%>
            <%= f.input :quantity, label: "En quel quantité ?" , as: :integer %>
            <%= f.input :category_id, label: "Le type de votre demande ?", as: :select, collection: Category.all, label_method: :name, label_value: :id %>
            <%= f.submit 'envoyer', class: 'btn btn-primary' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

<%# DROP DOWN PENDING ORDERS  %>

<%= render "shared/historique_client"%>