config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions" }
  root to: "pages#home"

  get '/choose_restaurant', to: 'pages#choose_restaurant'
  get '/assign_restaurant', to: 'pages#assign_restaurant'

  resources :sitting_areas, only: [:show] do
    resources :items, only: %i[create]
    resources :orders, only: %i[new show] do
      collection do
        get :add_order
        get :remove_order
      end
    end
  end

  resources :orders, only: %i[update destroy ] do
    member do
      post :toggle_status
    end
    collection do
      patch :update_all
    end
  end

  resources :restaurants, except: [:index]
end

app/views/shared/_banner_client.html.erb
<div class="top-restaurant-banner" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url('<%= cl_image_path restaurant.image.key, height: 300, crop: :fill %>');">
  <h3>Table <%= sitting_area.sitting_area_number %></h3>
  <%= link_to restaurant_path(restaurant), class: "text-decoration-none text-white restoname text-white" do %>
    <%= restaurant.name %>
  <% end %>
</div>

app/views/shared/_banner_owner.html.erb
<div class="top-restaurant-banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path restaurant.image.key, height: 300, crop: :fill %>');">
  <%= link_to sitting_area_path(@sitting_areas.first), class: "text-decoration-none text-white restoname text-white" do %>
    <%= restaurant.name %>
     <p class= "mb-0"><%= current_user.email.capitalize.split("@")[0] %></p>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_historique_client.html.erb
<div class="pending-orders">
  <h5 class="py-1 text-center"  >
    <% if (@pending_orders.count) == 0 %>
      0 Commandes en attente
    <% else  %>
      <%= @pending_orders.count %> Commandes en attente
    <% end %>
    <span class="btn btn-primary collapsed" data-bs-toggle="collapse" data-bs-target="#collapseExample-<%= @sitting_area.id %>">
      <i class="fa-solid fa-angle-down"></i>
    </span>
  </h5>

  <div class="collapse container-fluid" id="collapseExample-<%= @sitting_area.id %>">
    <div class="card-body mt-2">
      <% @pending_orders.each do |order| %>
        <div class="d-flex justify-content-between">
          <div>
            <div>
            <%= pluralize(order.quantity, order.item.name) %>
            </div>
            <small>Il y a  <%= order.find_time %> </small>
          </div>
          <div >
              <div class="badge bg-secondary">
                <%= format_status(order.status) %>
              </div>
              <div>
              <%= link_to "supprimer", order_path(order), class: "sup_btn  ", data: {turbo_method: :delete, turbo_confirm: 'Are you sure'} %>
              </div>
          </div>
        </div>
        <hr>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon ">
  <div class="container">
    <% if current_user %>
      <p class="mb-0">Bienvenu(e) <%= current_user.email.capitalize.split("@")[0] %></p>
      <%else%>
      <p> connectez vous</p>
    <%end %>
    <div class="">
      <button class="custom-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <% if user_signed_in? %>
            <li class="nav-item active">
              <%= link_to "Home", user_session_path, class: "nav-link" %>
          </li>
              <li class="nav-item">

                <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </li>
            <li class="nav-item dropdown">
              <%= image_tag "https://img1.freepng.fr/20180701/btv/kisspng-computer-icons-avatar-user-profile-man-avatars-5b38adb9f113b0.3674732815304411459875.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Rent", "#", class: "dropdown-item" %>
                <%= link_to "Booking", "#", class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/shared/_orders_detail.html.erb
<div class="ordered_card" data-bs-toggle="collapse" data-bs-target="#collapseExample-<%= user.id %>" aria-expanded="false" aria-controls="collapseExample">
  <div class="d-flex justify-content-between">
    <h3><%= user.email.capitalize.split("@")[0] %></h3>
    <i class="fa-solid fa-angle-down" style="font-size: 20px;"></i>
  </div>
  <strong><%= @restaurant.orders.where(status: "acceptée", employee: user.id).count + @restaurant.orders.where(status: "refusée", employee: user.id).count %></strong> commandes executées
  <div class="collapse" id="collapseExample-<%= user.id %>">
    <div class=" card-body mt-2 ">
      <% @orders.where(employee: user.id).select { |order| order.restaurant == @restaurant }.each do |order| %>
        <div class="d-flex justify-content-between mt-2 flex-column justify-content-start">
          <div class="d-flex justify-content-between">
            <div><%= pluralize(order.quantity, order.item.name) %></div>
            <span class="badge bg-secondary" style="font-size: 14px;"><%= order.status %></span>
          </div>
          <div class = "d-flex justify-content-between">
            <% time = distance_of_time_in_words(order.updated_at, order.created_at)  %>
            <% if (order.updated_at - order.created_at) >= 5.minutes %>
              <small class="elapsed-time-red">(temps d'attente de <%= time %>)</small>
            <% elsif (order.updated_at - order.created_at) >= 3.minutes %>
              <small class="elapsed-time-orange">(temps d'attente de <%= time %>)</small>
            <% else %>
              <small class="elapsed-time-green">(temps d'attente de <%= time %>)</small>
            <% end %>
          </div>
        </div>
        <hr class="my-hr">
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_recap_orders.html.erb
<hr>
<h5 class="mb-0 py-1">Commandes en attente</h5>
<% pending_orders.each do |order| %>
  <div class="py-1">
    <div class="d-flex justify-content-between">
      <%= order.quantity %> <%= order.item.name %>
      <div class="badge bg-secondary"><%= format_status(order.status) %></div>
    </div>
    <div class="d-flex justify-content-between">
      <small>(Add <%= order.find_time %>)</small>
      <div class="d-flex">
        <%= link_to "supprimer", order_path(order), class: "disabled pe-2", data: {turbo_method: :delete, turbo_confirm: 'Are you sure'} %>
        <%= link_to "modifier", new_sitting_area_order_path(@sitting_area, category_id: order.category.id) %>
      </div>
    </div>
  </div>
<% end %>

<hr>
<h5 class="mb-0 py-1">Historique des commandes</h5>
<% passed_orders.each do |order| %>
  <div class="py-1">
    <div class="d-flex justify-content-between">
      <div>
        <%= order.quantity %> <%= order.item.name %>
      </div>
      <div class="badge bg-secondary"><%= format_status(order.status) %></div>
    </div>
    <% if !order.employee.nil? %>
    <small>(Add <%= order.find_time %>) </small><small>pris en charge par <%= User.find(order.employee).email.capitalize.split("@")[0] %></small>
    <% end %>
  </div>
<% end %>