config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions" }
  root to: "pages#home"

  get '/choose_restaurant', to: 'pages#choose_restaurant'
  get '/assign_restaurant', to: 'pages#assign_restaurant'

  resources :sitting_areas, only: [:show] do
    resources :items, only: %i[create]
    resources :orders, only: %i[new show] do
      collection do
        get :add_order
        get :remove_order
      end
    end
  end

  resources :orders, only: %i[update destroy ] do
    member do
      post :toggle_status
    end
    collection do
      patch :update_all
    end
  end

  resources :restaurants, except: [:index]
end

app/models/order.rb
require 'dotiw'

class Order < ApplicationRecord
  belongs_to :item
  belongs_to :sitting_area
  has_one :restaurant, through: :sitting_area
  has_one :category, through: :item

  include ActionView::Helpers::DateHelper

  def find_time
    distance_of_time_in_words(Time.now, created_at)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @category = Category.find(params[:category_id])
    @sitting_area = SittingArea.find(params[:sitting_area_id])
    @order = Order.new
    @pending_orders = @sitting_area.orders.where(status: "en attente")
    @passed_orders = @sitting_area.orders - @pending_orders
    @restaurant = @sitting_area.restaurant
  end

  def add_order
    @order = Order.find_by(item_id: params[:item_id].to_i, sitting_area_id: params[:sitting_area_id].to_i, status: "en attente")
    if @order.nil?
      @order = Order.new(status: "en attente", quantity: 1)
      @order.item = Item.find(params[:item_id])
      @order.sitting_area = SittingArea.find(params[:sitting_area_id])
      if @order.save
        redirect_to new_sitting_area_order_path(@order.sitting_area, Order.new, category_id: @order.item.category.id)
      else
        render :new
      end
    else
      @order.quantity += 1
      @order.save
      redirect_to new_sitting_area_order_path(@order.sitting_area, Order.new, category_id: @order.item.category.id)
    end
  end

  def remove_order
    @order = Order.find_by(item_id: params[:item_id].to_i, sitting_area_id: params[:sitting_area_id].to_i, status: "en attente") # Find order
    if @order.quantity > 1
      @order.quantity -= 1 # decrement quantity
      @order.save # save
      redirect_to new_sitting_area_order_path(@order.sitting_area, Order.new, category_id: @order.item.category.id) # redirect av le submit
    else
      @order.destroy
      redirect_to new_sitting_area_order_path(@order.sitting_area, Order.new, category_id: @order.item.category.id) # redirect av le submit
    end
  end

  def update
    @order = Order.find(params[:id])
    @order.status = params[:order][:status]
    @order.employee = current_user.id
    @order.save
    redirect_to restaurant_path(@order.sitting_area.restaurant), status: :unprocessable_entity
  end

  def destroy
    @order = Order.find(params[:id])
    @sitting_area = @order.sitting_area
    @order.destroy
    redirect_to new_sitting_area_order_path(@sitting_area, Order.new)
  end

  def show
    @order = Order.find(params[:id])
    # @sitting_areas = @order.sitting_areas
  end

  def update_all
    status = params[:sitting_area][:status]
    @sitting_area = SittingArea.find(params[:sitting_area][:sitting_area].to_i)
    @sitting_area.orders.where(status: "en attente").update_all(status: status, employee: current_user.id)
    redirect_to restaurant_path(@sitting_area.restaurant), status: :unprocessable_entity
  end

  private

  def order_params
    params.require(:order).permit(:quantity, :item_id)
  end
end

app/views/orders/new.html.erb
<%= render "shared/banner_client", restaurant: @restaurant, sitting_area: @sitting_area %>
<%# Back btn %>
<%= link_to sitting_area_path(@sitting_area), class: "back-btn" do %>
  <i class="fa-solid fa-chevron-left"></i>
  <% end %>

<div class="container-fluid mb-5">
  <%# <%= render 'shared/recap_orders', pending_orders: @pending_orders, passed_orders: @passed_orders %>
  <div class="icone-item">
    <%= image_tag "#{@category.name}.png"%>
  </div>

  <hr>
  <h5 class="mb-0 py-1">Passer commande</h5>
  <hr>
  <% @category.items.where.not(custom: ("true")).each do |item| %>
    <%# <span><%= item.name %></span>
          <%# <%= image_tag "#{item.name}.png", style: 'height:40px;width:40px;' %>
    <div class="d-flex w-100 justify-content-between py-2">
      <%= item.name %>
      <div class="d-flex align-items-center category-item-number" >
        <% order = Order.where(item_id: item.id, sitting_area_id: params[:sitting_area_id]).last %>
        <%# font awsome btn - %>
        <%= link_to remove_order_sitting_area_orders_path(@sitting_area, item_id: item.id), class: "btn btn-primary minus #{ 'disabled' if order.nil? || order.status != "en attente"}" do %>
          <i class="fa-solid fa-minus"></i>
        <% end %>



        <div class="number px-2"><%= @sitting_area.orders.find_by(item: item, status: "en attente").nil? ? '0' : @sitting_area.orders.find_by(item: item, status: "en attente").quantity %></div>

        <%# font awsome btn + %>
        <%= link_to add_order_sitting_area_orders_path(@sitting_area, item_id: item.id), class: "plus" do %>
          <i class="fa-solid fa-plus" ></i>
        <% end %>

      </div>
    </div>
  <% end %>
  <hr>
</div>
<%= render "shared/historique_client"%>

app/views/orders/show.html.erb
<h1>Show of Order</h1>

<div class="container">
  <h1>Order Details</h1>

</div>