config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions" }
  root to: "pages#home"

  get '/choose_restaurant', to: 'pages#choose_restaurant'
  get '/assign_restaurant', to: 'pages#assign_restaurant'

  resources :sitting_areas, only: [:show] do
    resources :items, only: %i[create]
    resources :orders, only: %i[new show] do
      collection do
        get :add_order
        get :remove_order
      end
    end
  end

  resources :orders, only: %i[update destroy ] do
    member do
      post :toggle_status
    end
    collection do
      patch :update_all
    end
  end

  resources :restaurants, except: [:index]
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :sitting_areas, dependent: :destroy
  has_many :employees, class_name: "User"
  has_many :orders, through: :sitting_areas
  has_many :items
  has_one_attached :image
  has_many :users
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def show
    @restaurant = Restaurant.find(params[:id])
    @sitting_areas = @restaurant.sitting_areas
    @users = User.where(restaurant: @restaurant)
    @orders = Order.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.number_of_sitting_areas.times do |index|
      @restaurant.sitting_areas.new(sitting_area_number: index + 1)
    end
    if @restaurant.save
      @restaurant.users << current_user
      current_user.update(status: "owner") # ajout du status
      redirect_to restaurant_path(@restaurant), notice: 'restaurant was successfully created 😎.'
    else
      render :new
    end
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: 'restaurant was successfully updated 😎.'
    else
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_url, notice: 'restaurant was successfully destroyed 😎.'
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :image, :number_of_sitting_areas)
  end
end

app/views/restaurants/new.html.erb
<%# simple form avec btn qui pointe vers create d'un resto et input photo (cloudinary dans le cours)%>
<p>Add your Restaurant informations</p>
<%#  controller de resto %>

<%= simple_form_for @restaurant, url: restaurants_path, method: :post do |f| %>
  <%= f.input :name, label: 'Name' %>
  <%= f.input :address, label: 'Address' %>
  <%= f.input :number_of_sitting_areas, label: 'Number of Sitting Areas' %>
  <%= f.input :image, as: :file, label: 'Image' %>
  <%= f.submit 'Save', class: 'btn btn-primary' %>
<% end %>

app/views/restaurants/show.html.erb
<%= render "shared/banner_owner", restaurant: @restaurant, sitting_area: @sitting_area %>

<div class="btn-owner py-3">
  <nav>
    <div class="nav nav-tabs" id="nav-tab" role="tablist">
      <button class="nav-link active" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#nav-home" type="button" role="tab" aria-controls="nav-home" aria-selected="true">en cours</button>
      <button class="nav-link" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-profile" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">passées</button>
    </div>
  </nav>
</div>

<div class="tab-content mb-5" id="nav-tabContent">
  <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab" tabindex="0">
    <% @sitting_areas.each do |sitting_area| %>
      <% unless sitting_area.orders.where(status: "en attente").empty? %>
        <div class="ordered_card">
          <h3>Table <%= sitting_area.sitting_area_number %></h3>
          <% sitting_area.orders.each do |order|%>
            <% if order.status == "en attente" %>
              <div class="d-flex justify-content-between">
                <div class="d-flex flex-column align-items-start">
                  <div>
                    <%= pluralize(order.quantity, order.item.name) %>
                  </div>
                  <div class="d-flex gap-2 justify-content-between">
                    <% elapsed_time = Time.current - order.created_at %>
                    <%# HERE TO CHANGE THE TIME TO TURN IT RED %>
                    <% if elapsed_time >= 5.minutes %>
                      <small class="elapsed-time-red">(il y a <%= order.find_time %>)</small>
                    <%# HERE TO CHANGE THE TIME TO TURN IT ORANGE %>
                    <% elsif elapsed_time >= 2.minute %>
                      <small class="elapsed-time-orange">(il y a <%= order.find_time %>)</small>
                    <% else %>
                      <small>(il y a <%= order.find_time %>)</small>
                    <% end %>
                  </div>
                </div>
                <div class="d-flex justify-content-between">
                  <%= form_with model: order do |f| %>
                    <%= f.hidden_field :status, value: "refusée" %>
                     <%= button_tag type: "submit", class: "x-btn" do %>
                    <i class="fa-solid fa-xmark fa-2x"></i>
                  <% end %>
                  <% end %>
                  <%= form_with model: order do |f| %>
                    <%= f.hidden_field :status, value: "acceptée" %>
                    <%= button_tag type: "submit", class: "v-btn" do %>
                  <i class="fa-solid fa-check fa-2x"></i>
                <% end %>
                  <% end %>
                </div>
              </div>
              <hr class="my-hr">
            <% end %>
          <% end %>
          <div class="d-flex justify-content-end">
            <div class="d-flex " style="margin-left: 10px;">
              <%= simple_form_for :sitting_area, url: update_all_orders_path, method: :patch do |f| %>
                <%= f.hidden_field :sitting_area,  value: sitting_area.id %>
                <%= f.hidden_field :status,  value: 'refusée' %>
                <%= button_tag type: "submit", class: "btn r-btn" do %>
                  tout refuser
                <% end %>
              <% end %>
              <%= simple_form_for :sitting_area, url: update_all_orders_path, method: :patch do |f| %>
                <%= f.hidden_field :sitting_area,  value: sitting_area.id %>
                <%= f.hidden_field :status,  value: 'acceptée' %>
                <%= button_tag type: "submit", class: "btn a-btn" do %>
                  tout accepter
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab" tabindex="0">
    <% if current_user.status == "owner" %>
      <% @users.each do |user| %>
        <%= render "shared/orders_detail", user: user %>
      <% end %>
    <% else %>
      <%= render "shared/orders_detail", user: current_user %>
    <% end %>
  </div>
</div>